//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class intake_table
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> worker_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTime> intake_date { get; set; }
    }
}
