//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Tracking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Factory_Stock : DbContext
    {
        public DB_Factory_Stock()
            : base("name=DB_Factory_Stock")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<intake_table> intake_table { get; set; }
        public virtual DbSet<product_table> product_table { get; set; }
        public virtual DbSet<supplier_table> supplier_table { get; set; }
        public virtual DbSet<supply_table> supply_table { get; set; }
        public virtual DbSet<worker_table> worker_table { get; set; }
        public virtual DbSet<admin_table> admin_table { get; set; }
    }
}
