//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Tracking
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker_table
    {
        public int id { get; set; }
        public string identification { get; set; }
        public string name_surname { get; set; }
        public string rank { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string image { get; set; }
    }
}
